Sonarube-integerate

diff --git a/.github/workflows/Backend.yaml b/.github/workflows/Backend.yaml
--- a/.github/workflows/Backend.yaml
+++ b/.github/workflows/Backend.yaml
@@ -24,7 +24,7 @@ jobs:
 
 
 
-        
+
     # Run SonarQube Scan
     - name: SonarQube Scan
       uses: sonarsource/sonarqube-scan-action@v4
@@ -35,26 +35,19 @@ jobs:
         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
 
     # Wait for SonarQube Quality Gate status : Exit make to skip : exit 0
-    #- name: Check SonarQube Quality Gate status
-    #  run: |
-    #    QUALITY_GATE_STATUS=$(curl -s -X GET -u ${{ secrets.SONAR_TOKEN }} "https://sonarcloud.io/api/qualitygates/project_status?projectKey=Full-stack:Test" | jq -r '.projectStatus.status')
-    #   if [[ "$QUALITY_GATE_STATUS" != "OK" ]]; then
-    #     echo "Quality Gate failed. Code not allowed to be pushed to ECR."
-    #     exit 1    
-    #   fi
+    - name: Check SonarQube Quality Gate status
+      run: |
+       QUALITY_GATE_STATUS=$(curl -s -X GET -u ${{ secrets.SONAR_TOKEN }} "https://sonarcloud.io/api/qualitygates/project_status?projectKey=Full-stack:Test" | jq -r '.projectStatus.status')
+       if [[ "$QUALITY_GATE_STATUS" != "OK" ]]; then
+         echo "Quality Gate failed. Code not allowed to be pushed to ECR."
+         exit 1    
+       fi
 
 
 
 
 
-
-
-
-
-
-
-
-
+       
 
 
     # Login to Amazon ECR
